#!/usr/bin/env python3
"""Render the perf-grid ledger (qa/perf-grid.sh) as markdown tables.

    python qa/perf-grid-tables.py <out-dir> [--md <file>]

Deterministic: every number is read from <out-dir>/ledger.csv; the degenerate-output scan reads
the perf cells' .gen files (3-gram uniqueness of the generated tail). Rows whose status is not OK
and rows flagged DEGENERATE are listed and excluded from the comparison tables. Speculative cells
get a per-target-step rate: decode_tps / (1 + accept * n_draft) with n_draft = 2 (MTP, -n-max 2)
or 3 (DSpark, bs=4 verify tier), because with a fixed seed the arms' numerics still diverge, the
sampled text differs, and the decode figure scales with the acceptance the text happened to draw.
"""
import csv, io, os, re, sys, collections

out_dir = sys.argv[1]
md_path = None
if "--md" in sys.argv:
    md_path = sys.argv[sys.argv.index("--md") + 1]
ledger = os.path.join(out_dir, "ledger.csv")

rows = []
header_lines = []
with io.open(ledger, encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n")
        if line.startswith("#"):
            header_lines.append(line)
            continue
        rows.append(line)
reader = csv.DictReader(io.StringIO("\n".join(rows)))
R = list(reader)
for r in R:
    r["arm_full"] = r["arm"] + ("+pred" if r["predict"] == "1" else "") + ("+warm" if r["warm"] == "1" else "") + ("+noovl" if r["noovl"] == "1" else "")

# ---- degenerate-output scan (perf cells): 3-gram uniqueness of the generated tail
def gen_tail(cell, prompt_len):
    p = os.path.join(out_dir, cell + ".gen")
    if not os.path.exists(p):
        return None
    t = io.open(p, encoding="utf-8", errors="replace").read()
    t = re.sub(chr(27) + r"\[[0-9;]*m", "", t).replace("\r", "")
    return t[prompt_len:] if len(t) > prompt_len else t

PROMPT_LEN = {"512": 1709, "4k": 12850}   # bytes of prompt-512-v2.txt / prompt-4k-v2.txt (echoed by perf runs)
degenerate = {}
for r in R:
    if r["kind"] != "perf":
        continue
    g = gen_tail(r["cell"], PROMPT_LEN.get(r["prompt"], 0))
    if not g or len(g) < 80:
        continue
    toks = g.split()
    if len(toks) < 12:
        # a tail of one repeated non-space token (e.g. "////...") has almost no whitespace tokens
        degenerate[r["cell"]] = "no-words (%d chars, %d tokens)" % (len(g), len(toks))
        continue
    grams = [" ".join(toks[i:i + 3]) for i in range(len(toks) - 2)]
    uniq = len(set(grams)) / max(1, len(grams))
    top = collections.Counter(toks).most_common(1)[0][1] / len(toks)
    digits = sum(c.isdigit() for c in g) / len(g)
    if uniq < 0.35 or top > 0.30 or digits > 0.30:
        degenerate[r["cell"]] = "3-gram uniqueness %.2f, top token %.2f, digits %.2f" % (uniq, top, digits)

def ok(r):
    return r["status"] == "OK" and r["cell"] not in degenerate

N_DRAFT = {"mtp": 2, "dspark": 3, "none": 0}
def steps_per_s(r):
    try:
        acc = float(r["accept_pct"]) / 100.0
        return float(r["decode_tps"]) / (1.0 + acc * N_DRAFT.get(r["spec"], 0))
    except Exception:
        return None

ARM_ORDER = ["stock", "auto", "s0", "s1", "s2", "s3", "s4", "pool:fetch", "pool:fetch+pred", "pool:fetch+pred+warm",
             "pool:hybrid", "pool:hybrid+pred", "pool:hybrid+noovl", "pool:cpu_admit", "pool:cpu_admit+pred",
             "pool:cpu_admit+noovl", "pool:cpu_exec", "pool:fetch_on_2nd_miss", "pool:plan", "poolauto"]
def budgets_of(model):
    return ["4000", "8000", "14500"] if model.startswith("q35") else ["8000", "14500"]

L = []
def w(s=""):
    L.append(s)

w("# perf grid results: %s" % os.path.basename(out_dir.rstrip("/\\")))
w()
for h in header_lines:
    w("`%s`" % h)
w()
w("Generated by `qa/perf-grid-tables.py` from `ledger.csv`. Regime: GPC 2100 MHz, seed 1234, 128 decode tokens, prompts prompt-512-v2.txt (366/348 tokens) and prompt-4k-v2.txt (3978/3910 tokens). Cells: %d. Statuses: %s." % (
    len(R), ", ".join("%s %d" % (k, v) for k, v in sorted(collections.Counter(r["status"] for r in R).items(), key=lambda kv: -kv[1]))))
w()
w("## Excluded rows")
w()
w("| cell | reason |")
w("|---|---|")
for r in R:
    if r["status"] != "OK":
        w("| %s | %s (strategy_active=%s, vram_delta=%s) |" % (r["cell"], r["status"], r["strategy_active"], r["vram_peak_delta_mib"]))
for c, why in sorted(degenerate.items()):
    w("| %s | DEGENERATE output: %s |" % (c, why))
w()

def table_plain(model):
    w("## %s plain decode: prompt t/s / decode t/s (pool rows add h)" % model)
    w()
    buds = budgets_of(model)
    cols = [(b, p) for p in ["512", "4k"] for b in buds]
    w("| arm | " + " | ".join("%s/%s" % (b if b != "14500" else "full", p) for b, p in cols) + " |")
    w("|---|" + "---|" * len(cols))
    idx = {(r["arm_full"], r["mva"], r["prompt"]): r for r in R if r["kind"] == "perf" and r["model"] == model and r["spec"] == "none"}
    for a in ARM_ORDER:
        cells = []
        any_ = False
        for b, p in cols:
            r = idx.get((a, b, p))
            if r is None:
                cells.append("-"); continue
            any_ = True
            if not ok(r):
                cells.append("excluded (%s)" % ("DEGEN" if r["cell"] in degenerate else r["status"])); continue
            s = "%.0f / %.1f" % (float(r["prompt_tps"] or 0), float(r["decode_tps"] or 0))
            if r["h"]:
                s += " h=%s" % r["h"]
            if a in ("pool:plan", "poolauto") and r["miss_policy"]:
                s += " (%s)" % r["miss_policy"]
            cells.append(s)
        if any_:
            w("| %s | " % a + " | ".join(cells) + " |")
    w()

def table_spec(model, spec):
    w("## %s + %s speculative: decode t/s (accept %%) [target steps/s]" % (model, spec))
    w()
    buds = budgets_of(model)
    cols = [(b, p) for p in ["512", "4k"] for b in buds]
    w("| arm | " + " | ".join("%s/%s" % (b if b != "14500" else "full", p) for b, p in cols) + " |")
    w("|---|" + "---|" * len(cols))
    idx = {(r["arm_full"], r["mva"], r["prompt"]): r for r in R if r["kind"] == "perf" and r["model"] == model and r["spec"] == spec}
    # stock dspark runs at -fitb 3000 and is recorded at mva 3000: map it to the set's column by prompt
    for r in R:
        if r["kind"] == "perf" and r["model"] == model and r["spec"] == spec and r["arm"] == "stock" and r["mva"] == "3000":
            for b in buds:
                idx.setdefault(("stock", b, r["prompt"]), r)
    for a in ARM_ORDER:
        cells = []
        any_ = False
        for b, p in cols:
            r = idx.get((a, b, p))
            if r is None:
                cells.append("-"); continue
            any_ = True
            if not ok(r):
                cells.append("excluded (%s)" % ("DEGEN" if r["cell"] in degenerate else r["status"])); continue
            sp = steps_per_s(r)
            s = "%.1f (%s%%)" % (float(r["decode_tps"] or 0), r["accept_pct"][:4])
            if sp:
                s += " [%.1f]" % sp
            if r["mva"] == "3000":
                s += " @3000"
            if r["h"]:
                s += " h=%s" % r["h"]
            cells.append(s)
        if any_:
            w("| %s | " % a + " | ".join(cells) + " |")
    w()
    w("Prompt t/s for the same cells:")
    w()
    w("| arm | " + " | ".join("%s/%s" % (b if b != "14500" else "full", p) for b, p in cols) + " |")
    w("|---|" + "---|" * len(cols))
    for a in ["stock", "auto", "s3", "pool:fetch", "pool:hybrid", "pool:plan", "poolauto"]:
        cells = []
        for b, p in cols:
            r = idx.get((a, b, p))
            cells.append("-" if r is None or not ok(r) else "%.0f" % float(r["prompt_tps"] or 0))
        w("| %s | " % a + " | ".join(cells) + " |")
    w()

table_plain("q35")
table_plain("dsv4")
table_spec("q35mtp", "mtp")
table_spec("dsv4", "dspark")

w("## Correctness gates (32 tokens, greedy): md5 groups per (model, budget, prompt)")
w()
w("| model/budget/prompt | groups |")
w("|---|---|")
G = collections.defaultdict(lambda: collections.defaultdict(list))
for r in R:
    if r["kind"] == "gate":
        G[(r["model"], r["mva"], r["prompt"])][r["md5"]].append(r["arm_full"] + ("*" if r["status"] != "OK" else ""))
for k in sorted(G):
    groups = sorted(G[k].items(), key=lambda kv: -len(kv[1]))
    w("| %s/%s/%s | " % k + "; ".join("%s: %s" % (h, ", ".join(a)) for h, a in groups) + " |")
w()
w("`*` = status not OK. Stock is the reference; a different hash on a pshard arm is a near-tie flip unless the PPL mirror disagrees.")
w()
w("## Perplexity mirror (ppl-docs-v2.txt, c2048 x 8 chunks)")
w()
w("| model/budget | stock | legacy auto | pool fetch |")
w("|---|---|---|---|")
P = collections.defaultdict(dict)
for r in R:
    if r["kind"] == "ppl":
        P[(r["model"], r["mva"])][r["arm"]] = r["ppl"]
for k in sorted(P):
    w("| %s/%s | %s | %s | %s |" % (k[0], k[1], P[k].get("stock", "-"), P[k].get("auto", "-"), P[k].get("pool:fetch", "-")))
w()
w("## Pool counters (perf rows): h and misses/token")
w()
w("| cell | policy | slots | h | misses/token | decode t/s |")
w("|---|---|---|---|---|---|")
for r in R:
    if r["kind"] == "perf" and r["h"]:
        w("| %s | %s | %s | %s | %s | %s%s |" % (r["cell"], r["miss_policy"], r["pool_slots"], r["h"], r["misses_per_token"], r["decode_tps"], "" if ok(r) else " (excluded)"))
w()

text = "\n".join(L) + "\n"
if md_path:
    io.open(md_path, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote", md_path, "(%d lines; %d degenerate, %d non-OK)" % (len(L), len(degenerate), sum(1 for r in R if r["status"] != "OK")))
else:
    sys.stdout.write(text)
